---
title: "week4_lab"
output: html_document
date: "2023-11-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidymodels)
library(tidyverse)
```


```{r}
rm(list = ls(all = TRUE))

df = read_csv('../../../data/OriginalProcessedData.csv')

colnames(df) <- gsub("~","", colnames(df))

df$Activity = factor(df$Activity)

```

```{r}

ggplot(df, aes(x = Activity, fill = Activity))+geom_bar()

```

```{r}
ggplot(df, aes(x = ACCELEROMETER_X_mean, y = ACCELEROMETER_Y_mean, color = as.factor(Activity))) + geom_point()

```

```{r}
ggplot(df, aes(x = GRAVITY_X_mean, y = GRAVITY_Y_mean, color = as.factor(Activity))) + geom_point()

```

```{r}
library(Rtsne)

tsne <- df %>% 
  select(-Activity) %>% 
  Rtsne()

df = df %>% transform(tsne1 = tsne$Y[,1], tsne2 = tsne$Y[,2])

ggplot(df, aes(x = tsne1, y = tsne2, color = Activity)) + geom_point()
```


```{r}
df_split = initial_split(df)
df_train <- training(df_split)
df_test <- testing(df_split)
```

```{r}
knn_spec <- nearest_neighbor(
  mode = "classification",
  engine = "kknn",
  neighbors = 5
)
```

```{r}
knn_wf <- workflow() %>% 
  add_formula(Activity ~ GRAVITY_X_mean + GRAVITY_Y_mean) %>% 
  add_model(knn_spec) 
```

```{r}
knn_fit <-
  knn_wf %>% 
  fit(data = df_train)

knn_fit %>% 
  extract_fit_parsnip()
```

```{r}
folds <- vfold_cv(df_train, v = 5)

knn_rs <- fit_resamples(
  knn_wf,
  folds,
  control = control_resamples(save_pred = TRUE)
)

collect_metrics(knn_rs)
```

```{r}
tune_spec <- nearest_neighbor(
  mode = "classification",
  engine = "kknn",
  neighbors = tune()
)

neighbor_grid <- grid_regular(neighbors(), levels = 10)

tune_wf <- workflow() %>%
  add_formula(Activity ~ GRAVITY_X_mean + GRAVITY_Y_mean) %>%
  add_model(tune_spec)

tune_rs <- tune_grid(
  tune_wf,
  folds,
  grid = neighbor_grid,
  control = control_resamples(save_pred = TRUE)
)

#collect_metrics(tune_rs)
autoplot(tune_rs)
```
```{r}
chosen_n <- tune_rs %>%
  select_by_one_std_err(metric = "roc_auc", neighbors)

final_knn <- finalize_workflow(tune_wf, chosen_n)

knn_fit <- fit(final_knn, df_train)

knn_fit %>% 
  extract_fit_parsnip()
```


```{r}
knn_pred <- augment(knn_fit, new_data = df_test) %>% transform(correct = ifelse(.pred_class == Activity, 1, 0)) %>%
  relocate(.pred_class, Activity, correct)
```

```{r}
knn_pred %>%                # training set predictions
  accuracy(truth = Activity, .pred_class)
```

