---
title: "week11_lab"
output: html_document
date: "2023-11-07"
---

```{r setup, include=FALSE}
library(tidyverse)
```

```{r}
rm(list = ls(all = TRUE))

# Supervised learning

# Initialization
epochs <- 0

Inputs <- matrix(c(1, 0, 0, 0,
                   0, 1, 0, 0,
                   0, 0, 1, 0,
                   0, 0, 0, 1), ncol = 4, byrow = TRUE)

Targets <- matrix(c(1, 0,
                    1, 0,
                    0, 1,
                    0, 1), ncol = 2, byrow = TRUE)

W <- matrix(runif(8, -1, 1), nrow = 4, ncol = 2)

mse <- 100
Lrate <- 0.1

```

```{r}
vect=c()
while (mse > 0.005) {
  epochs <- epochs + 1
  errs <- rep(0, 4)

  for (n in 1:4) {
    In <- Inputs[n, ]
    Targ <- Targets[n, ]
    Out <- In %*% W
    Err <- Targ - Out
    errs[n] <- mean(Err^2)
    delta <- Lrate * In %*% Err
    W <- W + delta
  }

  mse <- mean(errs)
  vect <- c(vect, mse)
}

cat("Epochs:", epochs, "\n")
plot(1:length(vect), vect)

```


```{r}
# Test
for (n in 1:4) {
  In <- Inputs[n, ]
  cat("Test results for input", n, "\n")
  Out <- In %*% W
  print(Out)
  cat("Expected results for input", n, "\n")
  Targ <- Targets[n, ]
  print(Targ)
}
```

